import { DocumentItem, DocumentCategory, ExtractedEntity, UserProfile } from '../types';

// Convert a file to Base64 helper
const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const base64String = reader.result as string;
      // Remove the prefix (e.g., "data:application/pdf;base64,")
      const cleanBase64 = base64String.split(',')[1];
      resolve(cleanBase64);
    };
    reader.onerror = (error) => reject(error);
  });
};

interface GeminiAnalysisResult {
  title: string;
  category: DocumentCategory;
  issuer: string;
  summary: string;
  dateCompleted: string;
  tags: string[];
  extractedEntities: { type: string; value: string; confidence: number }[];
  rawText: string;
}

export const analyzeDocumentWithGemini = async (
  file: File,
  apiKey: string
): Promise<Partial<DocumentItem>> => {
  try {
    const base64Data = await fileToBase64(file);
    const mimeType = file.type || 'application/pdf';

    const prompt = `
      You are an elite OCR and Named Entity Recognition (NER) agent for the "MemoryVerse AI" digital identity platform.
      Analyze this uploaded document. Perform OCR to extract all readable text, and extract metadata.
      
      Respond STRICTLY with a valid JSON object matching this structure (do not include markdown wrapping or backticks, return ONLY the raw JSON):
      {
        "title": "extracted descriptive title of the document",
        "category": "One of: Projects | Skills | Certifications | Internships | Academics | Achievements | Research | Experience | Resume | Portfolio | Other",
        "issuer": "organization or authority that issued it",
        "summary": "a clear 2-3 sentence abstract summary of what this document proves or details",
        "dateCompleted": "YYYY-MM-DD completion date or date of document, default to today's date if not found",
        "tags": ["3-5 relevant technical tags"],
        "extractedEntities": [
          {
            "type": "One of: Skill | Project | Internship | Certification | College | CGPA | Achievement | Company | Date | Role",
            "value": "the extracted value",
            "confidence": 95
          }
        ],
        "rawText": "full extracted raw text transcript of the document"
      }
    `;

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                inlineData: {
                  mimeType: mimeType,
                  data: base64Data,
                },
              },
              {
                text: prompt,
              },
            ],
          },
        ],
        generationConfig: {
          responseMimeType: "application/json"
        }
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API Error: ${response.status} - ${errText}`);
    }

    const data = await response.json();
    const responseText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!responseText) {
      throw new Error("No response text returned from Gemini API.");
    }

    // Parse the JSON output
    const parsed: GeminiAnalysisResult = JSON.parse(responseText.trim());

    // Format extracted entities with IDs
    const formattedEntities: ExtractedEntity[] = (parsed.extractedEntities || []).map((e, idx) => ({
      id: `ent-gen-${Date.now()}-${idx}`,
      type: e.type as any,
      value: e.value,
      confidence: e.confidence || 95
    }));

    return {
      title: parsed.title || file.name,
      category: parsed.category || 'Other',
      issuer: parsed.issuer || 'Extracted Source',
      summary: parsed.summary || 'Summary generated by Gemini AI.',
      dateCompleted: parsed.dateCompleted || new Date().toISOString().split('T')[0],
      tags: parsed.tags || [],
      extractedEntities: formattedEntities,
      rawText: parsed.rawText || 'OCR stream text extracted successfully.',
      confidenceScore: 98
    };

  } catch (error) {
    console.error("Error in analyzeDocumentWithGemini:", error);
    throw error;
  }
};

export const generateRAGResponseWithGemini = async (
  query: string,
  documents: DocumentItem[],
  user: UserProfile,
  skills: string[],
  apiKey: string
): Promise<{ text: string; citations: { title: string; category: string; id: string }[] }> => {
  try {
    // Construct context details from current profile and uploaded vault documents
    const profileContext = `
      User Name: ${user.name}
      University: ${user.college}
      Branch/Degree: ${user.degree}
      CGPA: ${user.cgpa}
      Target Career Goal: ${user.targetRole}
      Skills Stack: ${skills.join(', ')}
      Bio: ${user.bio}
    `;

    const documentsContext = documents.map((doc, idx) => `
      Document [${idx + 1}]:
      ID: ${doc.id}
      Title: ${doc.title}
      Category: ${doc.category}
      Issuer: ${doc.issuer}
      Summary: ${doc.summary}
      Extracted Entities: ${doc.extractedEntities.map(e => `${e.type}: ${e.value}`).join(', ')}
      Raw Text: ${doc.rawText.slice(0, 400)}
    `).join('\n');

    const prompt = `
      You are the "MemoryVerse AI" Personal Career Intelligence Chatbot.
      You answer questions based strictly on the user's verified digital profile and uploaded documents.
      
      User Profile Context:
      ${profileContext}
      
      Uploaded Documents Context:
      ${documentsContext}
      
      User Query: "${query}"
      
      Provide a helpful, professional, and descriptive response. Formulate your answer using markdown.
      Also, return a JSON array containing citations of the documents that directly helped answer this query.
      
      Your response MUST follow this exact format:
      RESPONSE_TEXT: [Your markdown answer goes here]
      CITATIONS_JSON: [{"title": "document title", "category": "document category", "id": "document ID"}]
    `;

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`Gemini API Error: ${response.status}`);
    }

    const data = await response.json();
    const responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
    
    // Parse response format
    const responseMarker = "RESPONSE_TEXT:";
    const citationsMarker = "CITATIONS_JSON:";

    let textAnswer = responseText;
    let citations: { title: string; category: string; id: string }[] = [];

    if (responseText.includes(responseMarker) && responseText.includes(citationsMarker)) {
      const textStartIndex = responseText.indexOf(responseMarker) + responseMarker.length;
      const textEndIndex = responseText.indexOf(citationsMarker);
      textAnswer = responseText.slice(textStartIndex, textEndIndex).trim();

      const citationsText = responseText.slice(textEndIndex + citationsMarker.length).trim();
      try {
        citations = JSON.parse(citationsText);
      } catch (e) {
        citations = [];
      }
    }

    return {
      text: textAnswer,
      citations
    };

  } catch (error) {
    console.error("Error in generateRAGResponseWithGemini:", error);
    return {
      text: `Failed to fetch Gemini AI response. Please make sure your Gemini API Key in Settings is valid. Error: ${(error as Error).message}`,
      citations: []
    };
  }
};
